Traceback (most recent call last):
  File "/opt/jupyterhub/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas
partsdf = pandas.DataFrame(parts)
partsdf.set_axis(parts[0][:],axis=1,inplace=True)  # label the columns
partsdf.drop(0, axis=0, inplace = True) # remove the first row that held the column names
partsdf
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-8-8f4ae7259542>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mpandas[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mpartsdf[0m [0;34m=[0m [0mpandas[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mparts[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mpartsdf[0m[0;34m.[0m[0mset_axis[0m[0;34m([0m[0mparts[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m:[0m[0;34m][0m[0;34m,[0m[0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m[0minplace[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m  [0;31m# label the columns[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mpartsdf[0m[0;34m.[0m[0mdrop[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0minplace[0m [0;34m=[0m [0;32mTrue[0m[0;34m)[0m [0;31m# remove the first row that held the column names[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mpartsdf[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'parts' is not defined
NameError: name 'parts' is not defined

